version: '3.7'

networks:
  front:
    external: true
    name: proxy

services:
  web:
    build:
      context: ./web
    container_name: mikedilger-web
    networks:
      - front
    environment:
      VIRTUAL_HOST: local.mikedilger.co.uk
      TWITTER_ACCESS_TOKEN: ${TWITTER_ACCESS_TOKEN}
      TWITTER_ACCESS_SECRET: ${TWITTER_ACCESS_SECRET}
      TWITTER_CONSUMER_KEY: ${TWITTER_CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET: ${TWITTER_CONSUMER_SECRET}
      EVENTS_CALENDAR_URL: ${EVENTS_CALENDAR_URL}
    volumes:
      - ./web:/var/www/html
    restart: on-failure
